sample_rate: 16000
train_ds:
  manifest_filepath: null
  sample_rate: 16000
  batch_size: 32
  trim_silence: true
  max_duration: 16.7
  shuffle: true
  is_tarred: false
  tarred_audio_filepaths: null
validation_ds:
  manifest_filepath: null
  sample_rate: 16000
  batch_size: 32
  shuffle: false
test_ds:
  manifest_filepath:
  - /home/smajumdar/PycharmProjects/nemo-eval/nemo_eval/librispeech/manifests/dev_other.json
  sample_rate: 16000
  batch_size: 32
  shuffle: false
  num_workers: 12
  pin_memory: true
model_defaults:
  repeat: 5
  dropout: 0.0
  separable: true
  se: true
  se_context_size: -1
tokenizer:
  dir: /home/smajumdar/PycharmProjects/nemo-eval/nemo_beta_eval/asrset/manifests/asrset_1.4/tokenizers/no_appen/tokenizer_spe_unigram_v1024/
  type: bpe
  model_path: nemo:tokenizer.model
  vocab_path: nemo:vocab.txt
preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  sample_rate: 16000
  normalize: per_feature
  window_size: 0.025
  window_stride: 0.01
  window: hann
  features: 80
  n_fft: 512
  frame_splicing: 1
  dither: 1.0e-05
  pad_to: 16
  stft_conv: false
spec_augment:
  _target_: nemo.collections.asr.modules.SpectrogramAugmentation
  freq_masks: 2
  time_masks: 10
  freq_width: 27
  time_width: 0.05
encoder:
  _target_: nemo.collections.asr.modules.ConvASREncoder
  feat_in: 80
  activation: relu
  conv_mask: true
  jasper:
  - filters: 512
    repeat: 1
    kernel:
    - 5
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: false
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 11
    stride:
    - 2
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
    stride_last: true
    residual_mode: stride_add
  - filters: 512
    repeat: 5
    kernel:
    - 13
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 15
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 17
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 19
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 21
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 13
    stride:
    - 2
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
    stride_last: true
    residual_mode: stride_add
  - filters: 512
    repeat: 5
    kernel:
    - 15
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 17
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 19
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 21
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 23
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 25
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 25
    stride:
    - 2
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
    stride_last: true
    residual_mode: stride_add
  - filters: 512
    repeat: 5
    kernel:
    - 27
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 29
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 31
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 33
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 35
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 37
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 512
    repeat: 5
    kernel:
    - 39
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
    se: true
    se_context_size: -1
  - filters: 640
    repeat: 1
    kernel:
    - 41
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: false
    separable: true
    se: true
    se_context_size: -1
decoder:
  _target_: nemo.collections.asr.modules.ConvASRDecoder
  feat_in: 640
  num_classes: 1024
  vocabulary:
  - <unk>
  - s
  - ▁the
  - t
  - ▁a
  - ▁i
  - ''''
  - ▁and
  - ▁to
  - ed
  - d
  - ▁of
  - e
  - ▁in
  - ing
  - .
  - ▁it
  - ▁you
  - 'n'
  - ▁that
  - m
  - 'y'
  - er
  - ▁he
  - re
  - r
  - ▁was
  - ▁is
  - ▁for
  - ▁know
  - a
  - p
  - c
  - ','
  - ▁be
  - o
  - ▁but
  - ▁they
  - g
  - ▁so
  - ly
  - b
  - ▁s
  - ▁yeah
  - ▁we
  - ▁have
  - ▁re
  - ▁like
  - l
  - ▁on
  - ll
  - u
  - ▁with
  - ▁do
  - al
  - ▁not
  - ▁are
  - or
  - ar
  - le
  - ▁this
  - ▁as
  - es
  - ▁c
  - ▁de
  - f
  - in
  - i
  - ve
  - ▁uh
  - ent
  - ▁or
  - ▁what
  - ▁me
  - ▁t
  - ▁at
  - ▁my
  - ▁his
  - ▁there
  - w
  - ▁all
  - ▁just
  - h
  - ▁can
  - ri
  - il
  - k
  - ic
  - ▁e
  - ▁
  - ▁um
  - ▁don
  - ▁b
  - ▁had
  - ch
  - ation
  - en
  - th
  - ▁no
  - ▁she
  - it
  - ▁one
  - ▁think
  - ▁st
  - ▁if
  - ▁from
  - ter
  - ▁an
  - an
  - ur
  - ▁out
  - 'on'
  - ▁go
  - ck
  - ▁would
  - ▁were
  - ▁w
  - ▁will
  - ▁about
  - ▁right
  - ment
  - ▁her
  - te
  - ion
  - ▁well
  - ▁by
  - ce
  - ▁g
  - ▁oh
  - ▁up
  - ro
  - ra
  - ▁when
  - ▁some
  - ▁also
  - ▁their
  - ers
  - ow
  - ▁more
  - ▁time
  - ate
  - ▁has
  - ▁people
  - ▁see
  - ▁pa
  - el
  - ▁get
  - ▁ex
  - ▁mean
  - li
  - ▁really
  - v
  - ▁ra
  - ▁been
  - ▁said
  - '-'
  - la
  - ge
  - ▁how
  - ▁po
  - ir
  - ▁mo
  - ▁who
  - ▁because
  - ▁co
  - ▁other
  - ▁f
  - id
  - ol
  - ▁un
  - ▁now
  - ▁work
  - ist
  - us
  - ▁your
  - ▁them
  - ver
  - as
  - ne
  - ▁ca
  - lo
  - ▁fa
  - ▁him
  - ng
  - ▁good
  - ▁could
  - ▁pro
  - ive
  - ▁con
  - de
  - un
  - age
  - ▁ma
  - '?'
  - at
  - ▁ro
  - ▁ba
  - ▁then
  - ▁com
  - est
  - vi
  - ▁dis
  - ies
  - ance
  - ▁su
  - ▁even
  - ▁any
  - ut
  - ad
  - ul
  - ▁se
  - ▁two
  - ▁bu
  - ▁lo
  - ▁say
  - ▁la
  - ▁fi
  - is
  - ▁li
  - ▁over
  - ▁new
  - ▁man
  - ▁sp
  - ity
  - ▁did
  - ▁bo
  - ▁very
  - x
  - end
  - ▁which
  - ▁our
  - ▁after
  - ▁o
  - ke
  - ▁p
  - im
  - ▁want
  - ▁ha
  - ▁v
  - z
  - ▁where
  - ard
  - um
  - ▁into
  - ru
  - ▁di
  - ▁lot
  - ▁dr
  - mp
  - ▁day
  - ated
  - ci
  - ▁these
  - ▁than
  - ▁take
  - ▁kind
  - ▁got
  - ight
  - ▁make
  - ence
  - ▁pre
  - ▁going
  - ish
  - ▁k
  - able
  - ▁look
  - ti
  - per
  - ▁here
  - ▁en
  - ▁ah
  - ry
  - ▁too
  - ▁part
  - ant
  - one
  - ▁ho
  - ▁much
  - ▁way
  - ▁sa
  - ▁something
  - mo
  - ▁us
  - ▁th
  - ▁mhm
  - ▁mi
  - ▁off
  - pe
  - ▁back
  - les
  - ▁cr
  - ▁ri
  - ▁fe
  - und
  - ▁fl
  - port
  - ▁school
  - ▁ch
  - ▁should
  - ▁first
  - ▁only
  - ▁le
  - ot
  - tion
  - ▁little
  - ▁da
  - ▁hu
  - ▁d
  - me
  - ta
  - ▁down
  - ▁okay
  - ▁come
  - ain
  - ff
  - ▁car
  - co
  - ▁need
  - ture
  - ▁many
  - ▁things
  - ▁ta
  - qu
  - man
  - ty
  - iv
  - ▁year
  - he
  - ▁thing
  - ho
  - ▁singapore
  - po
  - ▁vi
  - ▁sc
  - ▁still
  - der
  - ▁hi
  - ▁never
  - ▁qu
  - ia
  - ▁fr
  - ▁min
  - ▁most
  - om
  - ful
  - ▁bi
  - ▁long
  - ig
  - ▁years
  - ous
  - ▁three
  - ▁play
  - ▁before
  - ▁pi
  - ical
  - ▁those
  - ▁comp
  - huh
  - ▁live
  - tor
  - ise
  - ▁old
  - am
  - rr
  - ▁sta
  - ▁n
  - ick
  - di
  - ma
  - ary
  - ction
  - ▁friend
  - ition
  - ▁gu
  - ▁through
  - pp
  - for
  - ie
  - ious
  - ▁sh
  - ▁home
  - lu
  - ▁high
  - ian
  - cu
  - ▁help
  - ▁give
  - ▁talk
  - ▁sha
  - ▁such
  - ▁didn
  - em
  - ▁may
  - ▁ga
  - ▁'
  - ▁gra
  - ▁guess
  - ▁every
  - ▁app
  - tic
  - ▁tra
  - ▁"
  - op
  - ▁made
  - '"'
  - ▁op
  - ▁own
  - ▁mar
  - 'no'
  - ▁ph
  - ▁life
  - ▁y
  - ak
  - ine
  - ▁pu
  - ▁place
  - ▁always
  - ▁start
  - ▁jo
  - ▁pe
  - ▁let
  - ▁name
  - ni
  - ▁same
  - ▁last
  - ▁cl
  - ph
  - ▁both
  - ▁pri
  - ities
  - ▁another
  - and
  - ▁al
  - ▁boy
  - ving
  - ▁actually
  - ▁person
  - ▁went
  - ▁yes
  - ca
  - ally
  - ▁h
  - ▁great
  - ▁thought
  - ▁used
  - act
  - ▁feel
  - ward
  - ▁different
  - ▁cons
  - ▁show
  - ▁watch
  - ▁being
  - ▁money
  - ay
  - ▁try
  - ▁why
  - ▁big
  - ens
  - ▁cha
  - ▁find
  - ▁hand
  - ▁real
  - ▁four
  - ial
  - ▁ne
  - ▁che
  - ▁read
  - ▁five
  - ▁family
  - ag
  - ▁change
  - ▁add
  - ha
  - ▁put
  - par
  - lic
  - side
  - ▁came
  - ▁under
  - ness
  - ▁per
  - j
  - ▁around
  - ▁end
  - ▁house
  - if
  - ▁while
  - vo
  - ▁act
  - ▁happen
  - ▁plan
  - mit
  - ▁far
  - ▁tri
  - ▁ten
  - ▁du
  - ▁win
  - ▁tea
  - ze
  - ▁better
  - ▁sure
  - ▁mu
  - ▁use
  - ▁anything
  - ▁love
  - ▁world
  - ▁hard
  - ure
  - ▁does
  - ▁war
  - ▁stuff
  - ▁ja
  - ▁must
  - min
  - gg
  - ▁ru
  - ▁care
  - ▁tell
  - ▁pl
  - ▁doing
  - ▁probably
  - ▁found
  - ative
  - ▁point
  - ach
  - ▁ju
  - ip
  - ▁again
  - ▁interest
  - ▁state
  - ▁week
  - na
  - ▁might
  - ▁pretty
  - ▁ki
  - ▁fo
  - ber
  - ▁am
  - line
  - led
  - ▁six
  - ▁acc
  - ▁bri
  - ▁call
  - ▁sw
  - ▁each
  - ▁business
  - ▁keep
  - ▁away
  - cause
  - ▁pass
  - ▁va
  - ▁children
  - ▁pay
  - ▁count
  - ▁public
  - ▁everything
  - land
  - ▁though
  - ▁men
  - bo
  - ▁young
  - ▁na
  - ▁move
  - ough
  - ating
  - com
  - ▁month
  - ton
  - ▁close
  - ▁few
  - '!'
  - ▁maybe
  - ▁imp
  - son
  - ▁grow
  - ▁u
  - ▁turn
  - ible
  - ▁em
  - ▁air
  - ▁ever
  - our
  - ▁sea
  - ▁fun
  - ▁government
  - ▁miss
  - ▁done
  - ▁next
  - ▁kids
  - ▁cor
  - ▁set
  - ▁run
  - way
  - ▁wa
  - ▁getting
  - ▁eight
  - ▁open
  - ▁job
  - ▁problem
  - ook
  - ▁night
  - ▁learn
  - ▁book
  - ual
  - ▁ti
  - ▁best
  - cept
  - ▁during
  - ▁small
  - ex
  - ▁without
  - ▁water
  - ▁trans
  - ▁course
  - ▁once
  - ▁sit
  - ▁area
  - ▁country
  - ▁mister
  - ▁nothing
  - ▁whole
  - ▁believe
  - ▁service
  - ▁took
  - ▁face
  - ▁bad
  - ▁later
  - ▁head
  - ▁called
  - ▁seven
  - ▁art
  - ▁since
  - ▁er
  - ▁fact
  - ▁city
  - ▁market
  - ▁hour
  - ▁continue
  - ship
  - ▁invest
  - ▁exactly
  - ▁large
  - ▁true
  - ▁nine
  - ▁sub
  - ▁having
  - ▁game
  - va
  - ▁lu
  - ▁conf
  - ▁case
  - ▁doesn
  - ▁certain
  - ▁wi
  - ▁law
  - ▁else
  - fi
  - ▁left
  - ▁enough
  - ▁second
  - ▁gonna
  - ▁food
  - ▁hope
  - ▁saw
  - ▁between
  - ▁je
  - bi
  - ▁girl
  - ▁company
  - ▁able
  - ▁expect
  - ▁told
  - ▁stand
  - ▁group
  - ▁main
  - ▁walk
  - ▁cause
  - ▁however
  - ▁number
  - ▁follow
  - ▁near
  - ▁yet
  - ▁sometimes
  - ▁train
  - ▁lead
  - ▁system
  - ▁remain
  - ▁develop
  - gra
  - ▁word
  - ▁exc
  - ▁together
  - ▁consider
  - ▁town
  - ▁less
  - ator
  - ▁important
  - ▁remember
  - ▁free
  - ▁quite
  - ▁understand
  - ▁bra
  - ▁support
  - ▁idea
  - ▁stop
  - ▁reason
  - ▁nice
  - ▁mm
  - ▁agree
  - ▁low
  - ▁against
  - ▁issue
  - ▁become
  - ▁today
  - ▁side
  - ▁student
  - ▁matter
  - ▁question
  - ▁mother
  - ▁father
  - ▁hundred
  - ▁sort
  - ▁eat
  - ▁already
  - ▁rest
  - ▁line
  - ▁asked
  - ▁include
  - ▁upon
  - ▁office
  - ▁won
  - ▁class
  - ▁wait
  - ▁twenty
  - ▁half
  - ▁light
  - ▁price
  - ▁almost
  - ash
  - ▁child
  - ▁sign
  - ▁least
  - ▁several
  - press
  - ▁either
  - ▁minute
  - ▁himself
  - ▁parents
  - ▁room
  - ▁whatever
  - ▁general
  - ▁cost
  - ▁among
  - ▁direct
  - ▁computer
  - ▁appear
  - ▁meet
  - ▁ski
  - ▁return
  - ▁couple
  - ▁product
  - ▁suppose
  - ▁definitely
  - ▁america
  - ▁term
  - ▁usually
  - ▁strong
  - ▁current
  - ▁arm
  - ▁speak
  - ▁local
  - ▁south
  - ▁experience
  - ▁full
  - ▁north
  - ▁elect
  - ▁leave
  - ▁provide
  - qui
  - ▁power
  - ▁movie
  - ▁everyone
  - ▁making
  - ▁member
  - ▁woman
  - ▁somebody
  - ▁wonder
  - ▁short
  - ▁health
  - ▁police
  - ▁bank
  - ▁until
  - ▁companies
  - ▁everybody
  - ▁knew
  - ▁program
  - ▁music
  - ▁york
  - ▁land
  - ▁doctor
  - ▁answer
  - ▁building
  - ▁employ
  - ▁travel
  - ▁major
  - ▁seems
  - ▁safe
  - gue
  - ▁college
  - ▁along
  - ▁clear
  - ▁especially
  - ▁umhu
  - ▁result
  - ▁type
  - ▁court
  - ▁black
  - ▁hold
  - ▁myself
  - ▁education
  - ▁social
  - ▁enjoy
  - ▁became
  - ▁whether
  - ▁morning
  - ▁difficult
  - ▁shi
  - ▁felt
  - ▁husband
  - ▁white
  - ▁taking
  - ▁million
  - ▁require
  - ▁early
  - ency
  - ▁visit
  - ▁level
  - ▁brother
  - ▁married
  - ▁further
  - ▁affect
  - ▁serve
  - ▁present
  - ▁park
  - ▁effect
  - ▁wife
  - ▁teacher
  - ▁cannot
  - ▁community
  - ▁street
  - ▁period
  - ▁national
  - ▁view
  - ▁future
  - ▁daughter
  - ▁situation
  - ▁grand
  - ▁success
  - ▁perform
  - ▁concern
  - ▁complete
  - ▁example
  - ized
  - ▁thousand
  - ▁increase
  - ▁began
  - ▁final
  - ▁east
  - ▁sense
  - ▁charge
  - ▁record
  - ▁born
  - ▁instead
  - ▁receive
  - ▁women
  - ▁across
  - ▁information
  - ▁although
  - ▁process
  - ▁condition
  - ▁security
  - ▁treat
  - ▁funny
  - ▁custom
  - ▁cold
  - ▁behind
  - ified
  - ▁ground
  - cycl
  - ▁depend
  - ▁themselves
  - ▁design
  - ▁slow
  - ▁third
  - ▁smoke
  - ▁wrong
  - ▁project
  - ▁space
  - ▁drink
  - ▁particular
  - ▁listen
  - ▁thirty
  - ▁special
  - ability
  - ▁improve
  - ▁attack
  - ▁happy
  - ▁strange
  - ▁english
  - ▁value
  - ▁brought
  - ▁private
  - ▁account
  - ▁china
  - ▁spoke
  - ▁foreign
  - ▁possible
  - ▁author
  - ▁circ
  - ▁voice
  - ▁figure
  - ▁control
  - ▁according
  - ▁green
  - ▁university
  - ▁language
  - ▁please
  - ▁animal
  - ▁church
  - ▁society
  - ▁dream
  - ’
  - q
  - ':'
  - ;
  - —
  - ‘
  - ”
  - _
  - '3'
  - '8'
  - <
  - '>'
  - '1'
  - –
  - '7'
  - (
  - )
  - '0'
  - '2'
  - '4'
  - +
  - '&'
  - '5'
  - '9'
  - ü
  - é
  - /
  - á
  - ó
  - ō
  - ú
  - ']'
  - â
  - í
  - ã
  - ð
  - ā
  - ć
  - č
  - š
  - è
  - ë
  - '`'
  - ç
  - ū
  - ạ
  - ø
  - '='
  - à
  - ł
  - α
  - ô
  - к
  - '}'
  - å
  - ă
  - и
  - ī
  - π
  - œ
  - \
  - '['
  - ñ
  - ß
  - ö
  - ä
  - '6'
  - з
  - н
  - û
  - '%'
  - '{'
  - ¡
  - æ
  - ê
  - þ
  - ę
  - ě
  - ğ
  - ń
  - ő
  - ř
  - ž
  - ʻ
  - в
  - е
  - й
  - л
  - ь
  - χ
  - “
optim:
  name: novograd
  lr: 0.05
  betas:
  - 0.8
  - 0.25
  weight_decay: 0.001
  sched:
    name: CosineAnnealing
    warmup_steps: 1000
    min_lr: 1.0e-06
    max_steps: 100
target: nemo.collections.asr.models.ctc_bpe_models.EncDecCTCModelBPE
nemo_version: 1.20.0
decoding:
  strategy: greedy
  preserve_alignments: null
  compute_timestamps: null
  word_seperator: ' '
  ctc_timestamp_type: all
  batch_dim_index: 0
  greedy:
    preserve_alignments: false
    compute_timestamps: false
    preserve_frame_confidence: false
    confidence_method_cfg: null
  beam:
    beam_size: 4
    search_type: default
    preserve_alignments: false
    compute_timestamps: false
    return_best_hypothesis: true
    beam_alpha: 1.0
    beam_beta: 0.0
    kenlm_path: null
    flashlight_cfg:
      lexicon_path: null
      boost_path: null
      beam_size_token: 16
      beam_threshold: 20.0
      unk_weight: -.inf
      sil_weight: 0.0
    pyctcdecode_cfg:
      beam_prune_logp: -10.0
      token_min_logp: -5.0
      prune_history: false
      hotwords: null
      hotword_weight: 10.0
  confidence_cfg:
    preserve_frame_confidence: false
    preserve_token_confidence: false
    preserve_word_confidence: false
    exclude_blank: true
    aggregation: min
    method_cfg:
      name: entropy
      entropy_type: tsallis
      temperature: 0.33
      entropy_norm: exp
  temperature: 1.0
